version: '3'

tasks:
  gen-protoc:
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative protoc/*.proto

  gen-gogo-pb:
    cmds:
      - protoc --gofast_out=. gogo_protobuf/*.proto

  gen-example:
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative example/*.proto

  gen-streaming:
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative streaming/*.proto